### ISSUE TITLE
 train  code

### ISSUE THREAD

**Issue by soin-yu** [HaomingCai/CUGAN#1]
hello, I am trying to denoise with different medical ratio, I think your work may be very helpful, would you mind providing your train codes.

Thank you!

**Comment by HaomingCai** [comment]
> hello, I am trying to denoise with different medical ratio, I think your work may be very helpful, would you mind providing your train codes.
> 
> Thank you!

Thanks for paying attention to CUGAN.
I will update this codebase and release the train codes this week. 

If there is anything else I can help you with, please let me know.
